In [ ]:
import pandas as pd
adult = pd.read_csv("adult.csv")
adult.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [ ]:
adult.replace("?", pd.NA, inplace=True)
adult.isnull().sum()

age                   0
workclass          2799
fnlwgt                0
education             0
educational-num       0
marital-status        0
occupation         2809
relationship          0
race                  0
gender                0
capital-gain          0
capital-loss          0
hours-per-week        0
native-country      857
income                0
dtype: int64

In [ ]:
adult.dropna(inplace=True)

In [ ]:
categorical_cols = adult.select_dtypes(include=['object']).columns

adult_encoded = pd.get_dummies(adult, columns=categorical_cols, drop_first=True)

In [ ]:
num_cols = adult_encoded.select_dtypes(include=['int64', 'float64']).columns

In [ ]:
Q1 = adult_encoded[num_cols].quantile(0.25)
Q3 = adult_encoded[num_cols].quantile(0.75)
IQR = Q3 - Q1

In [ ]:
adult_encoded = adult_encoded[
    ~((adult_encoded[num_cols] < (Q1 - 1.5 * IQR)) |
      (adult_encoded[num_cols] > (Q3 + 1.5 * IQR))).any(axis=1)
]

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
adult_minmax = scaler.fit_transform(adult_encoded)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
adult_standard = scaler.fit_transform(adult_encoded)